name: CI • Pytest

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  tests:
    name: Python ${{ matrix.python-version }} • ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"     # يفعّل كاش pip تلقائيًا

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            echo "No requirements.txt found — installing minimal test deps"
          fi
          python -m pip install pytest
        shell: bash

      # على ويندوز، استخدم shell PowerShell لأوامر تعدد الأسطر إن رغبت
      - name: Run tests (pytest)
        run: |
          echo "PYTHONPATH=." >> $GITHUB_ENV
          python -m pytest -q
        shell: bash
